version: '3.6'
services:
  corsair:
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
      - "4010:4000"
    restart: always
    volumes:
      - ./1.meshrc.yaml:/work/.meshrc.yaml
  gateway:
    image: xmorse/apollo-federation-gateway
    ports:
      - "4000:80"
    depends_on:
      - corsair
    restart: always
    environment:
      - URL_0=http://corsair:4000/graphql
