version: '3.6'
services:
  postgres:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  flyway:
    image: flyway/flyway:6.4.3
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
  original-service:
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
      - "4000:4000"
    depends_on:
      - flyway
    restart: always
    volumes:
      - ./0.meshrc.yaml:/work/.meshrc.yaml
  federation-defining-service:
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
      - "4010:4000"
    depends_on:
      - original-service
    restart: always
    volumes:
      - ./1.meshrc.yaml:/work/.meshrc.yaml
  federation-extending-service:
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
      - "4030:4000"
    depends_on:
      - original-service
    restart: always
    volumes:
      - ./2.meshrc.yaml:/work/.meshrc.yaml
  federation-gateway-service:
    image: xmorse/apollo-federation-gateway
    ports:
      - "4040:80"
    depends_on:
      - federation-defining-service
      - federation-extending-service
    restart: always
    environment:
      - URL_0=http://federated-defining-service:4000/graphql
      - URL_1=http://federated-extending-service:4000/graphql

